### Get all products
GET http://localhost:8080/products
Content-Type: application/json

###

### Get a product by ID
GET http://localhost:8080/products/1
Content-Type: application/json

###

### Create a new product

POST http://localhost:8080/products
Content-Type: application/json

{
  "name": "New Product",
  //"description": "This is a new product.",
  "price": 25.50,
  "stockQuantity": 100,
  "category": [
    {"name": "hello"},
    {"name": "hello2"}
  ]
}

### Update a product
PUT http://localhost:8080/products/1
Content-Type: application/json

{
  "id": 1,
  "name": "Updated Product",
  "description": "Updated description.",
  "price": 10,
  "stockQuantity": 200,
  "category": [
    {"id": 1, "name": "this"},
    {"id": 2, "name": "that"}
  ]
}

###

### Update product stock
PATCH http://localhost:8080/products/1/update-stock
Content-Type: application/json

{
  "id": 1,
  "stockQuantity": 900
}